name: AutoBuild

on:
  push:
    branches-ignore:
      - master
      
jobs:
  build:
    name: AutoBuild on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Pack release version
      run: dotnet pack --configuration Release
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push bin/Release/frendstask.*.nupkg --api-key ${{secrets.NUGET_PUBLISH_TOKEN}} --source https://nuget.pkg.github.com/cellza/index.json
